[package]
name = "mandelbrot-rs"
version = "0.1.0"
authors = ["Robert Serrano Kobylyansky <sk.robchik@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11"
log = "0.4"
pixels = "0.15"
winit = "0.30"
winit_input_helper = "0.17"
num-complex = "0.4"
rayon = "1"
krnl = { git = "https://github.com/skrobchik/krnl.git", branch = "main" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_arch, values("spirv"))',
    'cfg(krnlc)',
    'cfg(doc_cfg)',
] }
