[workspace]
resolver = "2"
members = ["app", "shaders"]

[workspace.dependencies]
env_logger = "0.11"
log = "0.4"
pixels = "0.17"
winit = "0.30"
winit_input_helper = "0.17"
num-complex = "0.4"
rayon = "1"
spirv-std = "0.9"
spirv-builder = "0.10.0-alpha.1"

[profile.release.build-override]
opt-level = 3
codegen-units = 16

[profile.dev.build-override]
opt-level = 3
